In [1]:
import pandas as pd

Inconsistency Handling

In [3]:
#df[Column_name].value_counts()
#df[Column_name] = df[Column_name].str.title()
#df[Column_name] = df[Column_name].str.strip()
#df[Column_name] = df[Column_name].str.title().str.strip()

Time Series Operations

In [4]:
# Convert strings to date and time format
#df["date_column"] = pd.to_datetime(df["Date_column"])

In [8]:
date = pd.to_datetime("2026-10-24")
print(date)

2026-10-24 00:00:00

In [42]:
data = {
    "Date": ["2025-01-01", "2025-01-02", "2025-01-03", "2025-01-04", "2025-01-05"],
    "Sales": [5000,6500,4200,7000,5500]
}
df = pd.DataFrame(data)
print(df)
print(df.dtypes)
print()
df["Date"] = pd.to_datetime(df["Date"])
print(df)
print(df.dtypes)

         Date  Sales
0  2025-01-01   5000
1  2025-01-02   6500
2  2025-01-03   4200
3  2025-01-04   7000
4  2025-01-05   5500
Date     object
Sales     int64
dtype: object

        Date  Sales
0 2025-01-01   5000
1 2025-01-02   6500
2 2025-01-03   4200
3 2025-01-04   7000
4 2025-01-05   5500
Date     datetime64[ns]
Sales             int64
dtype: object

In [20]:
#Generating dates synthetically
dates = pd.date_range(start = "2025-01-01", end = "2025-01-31")
print(dates)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12',
               '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16',
               '2025-01-17', '2025-01-18', '2025-01-19', '2025-01-20',
               '2025-01-21', '2025-01-22', '2025-01-23', '2025-01-24',
               '2025-01-25', '2025-01-26', '2025-01-27', '2025-01-28',
               '2025-01-29', '2025-01-30', '2025-01-31'],
              dtype='datetime64[ns]', freq='D')

In [21]:
dates = pd.date_range(start = "2025-02-01", periods=28)
print(dates)

DatetimeIndex(['2025-02-01', '2025-02-02', '2025-02-03', '2025-02-04',
               '2025-02-05', '2025-02-06', '2025-02-07', '2025-02-08',
               '2025-02-09', '2025-02-10', '2025-02-11', '2025-02-12',
               '2025-02-13', '2025-02-14', '2025-02-15', '2025-02-16',
               '2025-02-17', '2025-02-18', '2025-02-19', '2025-02-20',
               '2025-02-21', '2025-02-22', '2025-02-23', '2025-02-24',
               '2025-02-25', '2025-02-26', '2025-02-27', '2025-02-28'],
              dtype='datetime64[ns]', freq='D')

In [37]:
dates = pd.date_range(start = "2025-01-01", periods=10,freq="D") #Date
print(dates)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [38]:
dates = pd.date_range(start = "2025-01-01", periods=10,freq="YS") #Year Start
print(dates)

DatetimeIndex(['2025-01-01', '2026-01-01', '2027-01-01', '2028-01-01',
               '2029-01-01', '2030-01-01', '2031-01-01', '2032-01-01',
               '2033-01-01', '2034-01-01'],
              dtype='datetime64[ns]', freq='YS-JAN')

In [27]:
dates = pd.date_range(start = "2025-01-01", periods=10,freq="YE") #Year End
print(dates)

DatetimeIndex(['2025-12-31', '2026-12-31', '2027-12-31', '2028-12-31',
               '2029-12-31', '2030-12-31', '2031-12-31', '2032-12-31',
               '2033-12-31', '2034-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')

In [28]:
dates = pd.date_range(start = "2025-01-01", periods=10,freq="MS") #Month Start
print(dates)

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01', '2025-07-01', '2025-08-01',
               '2025-09-01', '2025-10-01'],
              dtype='datetime64[ns]', freq='MS')

In [29]:
dates = pd.date_range(start = "2025-01-01", periods=10,freq="ME") #Month End
print(dates)

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30', '2025-10-31'],
              dtype='datetime64[ns]', freq='ME')

In [30]:
dates = pd.date_range(start = "2025-01-01", periods=10,freq="h") #Hours
print(dates)

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 01:00:00',
               '2025-01-01 02:00:00', '2025-01-01 03:00:00',
               '2025-01-01 04:00:00', '2025-01-01 05:00:00',
               '2025-01-01 06:00:00', '2025-01-01 07:00:00',
               '2025-01-01 08:00:00', '2025-01-01 09:00:00'],
              dtype='datetime64[ns]', freq='h')

In [33]:
dates = pd.date_range(start = "2025-01-01", periods=10,freq="min") #minutes
print(dates)

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 00:01:00',
               '2025-01-01 00:02:00', '2025-01-01 00:03:00',
               '2025-01-01 00:04:00', '2025-01-01 00:05:00',
               '2025-01-01 00:06:00', '2025-01-01 00:07:00',
               '2025-01-01 00:08:00', '2025-01-01 00:09:00'],
              dtype='datetime64[ns]', freq='min')

In [36]:
dates = pd.date_range(start = "2025-01-01", periods=10,freq="s") #Seconds
print(dates)

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 00:00:01',
               '2025-01-01 00:00:02', '2025-01-01 00:00:03',
               '2025-01-01 00:00:04', '2025-01-01 00:00:05',
               '2025-01-01 00:00:06', '2025-01-01 00:00:07',
               '2025-01-01 00:00:08', '2025-01-01 00:00:09'],
              dtype='datetime64[ns]', freq='s')

In [43]:
import numpy as np
dates = pd.date_range(start = "2025-01-01", periods=30,freq="D")
sales = np.random.randint(2000,10000,size = 30)
df2 = pd.DataFrame({"Date":dates,"Sales":sales})
print(df2)

         Date  Sales
0  2025-01-01   2226
1  2025-01-02   5885
2  2025-01-03   6189
3  2025-01-04   6126
4  2025-01-05   5172
5  2025-01-06   3041
6  2025-01-07   7867
7  2025-01-08   4009
8  2025-01-09   9047
9  2025-01-10   9888
10 2025-01-11   6803
11 2025-01-12   6672
12 2025-01-13   4320
13 2025-01-14   5129
14 2025-01-15   5338
15 2025-01-16   8532
16 2025-01-17   4472
17 2025-01-18   3789
18 2025-01-19   9130
19 2025-01-20   8712
20 2025-01-21   8039
21 2025-01-22   2740
22 2025-01-23   4887
23 2025-01-24   2930
24 2025-01-25   3105
25 2025-01-26   7506
26 2025-01-27   4133
27 2025-01-28   9941
28 2025-01-29   5360
29 2025-01-30   8124

In [45]:
df["Year"] = df["Date"].dt.year
print(df)

        Date  Sales  Year
0 2025-01-01   5000  2025
1 2025-01-02   6500  2025
2 2025-01-03   4200  2025
3 2025-01-04   7000  2025
4 2025-01-05   5500  2025

In [46]:
df.groupby(df['Date'].dt.year)["Sales"].sum()

Date
2025    28200
Name: Sales, dtype: int64

In [47]:
df["Month"] = df["Date"].dt.month
print(df)

        Date  Sales  Year  Month
0 2025-01-01   5000  2025      1
1 2025-01-02   6500  2025      1
2 2025-01-03   4200  2025      1
3 2025-01-04   7000  2025      1
4 2025-01-05   5500  2025      1

In [51]:
df[df["Date"].dt.month == 1]

        Date  Sales  Year  Month
0 2025-01-01   5000  2025      1
1 2025-01-02   6500  2025      1
2 2025-01-03   4200  2025      1
3 2025-01-04   7000  2025      1
4 2025-01-05   5500  2025      1

In [54]:
print(df["Date"].dt.month_name())

0    January
1    January
2    January
3    January
4    January
Name: Date, dtype: object

In [55]:
print(df["Date"].dt.day)

0    1
1    2
2    3
3    4
4    5
Name: Date, dtype: int32

In [56]:
print(df["Date"].dt.day_name())

0    Wednesday
1     Thursday
2       Friday
3     Saturday
4       Sunday
Name: Date, dtype: object

In [57]:
df = pd.DataFrame({
    "DateTime": pd.to_datetime(["2025-01-01 08:30:15", "2025-01-01 10:45:20", "2025-01-01 14:20:30", "2025-01-01 18:10:45"]),
    "Sales": [2000,3500,5000,4200]
})
print(df)

             DateTime  Sales
0 2025-01-01 08:30:15   2000
1 2025-01-01 10:45:20   3500
2 2025-01-01 14:20:30   5000
3 2025-01-01 18:10:45   4200

In [58]:
df["Hours"] = df['DateTime'].dt.hour
print(df["Hours"])

0     8
1    10
2    14
3    18
Name: Hours, dtype: int32

In [59]:
print(df['DateTime'].dt.minute)

0    30
1    45
2    20
3    10
Name: DateTime, dtype: int32

In [62]:
print(df['DateTime'].dt.second)

0    15
1    20
2    30
3    45
Name: DateTime, dtype: int32

In [64]:
dates = pd.date_range(start = "2020-01-01", periods=60, freq="ME")
sales = np.random.randint(2000,10000,size = 60)
df = pd.DataFrame({"Date":dates,"Sales":sales})
print(df)

         Date  Sales
0  2020-01-31   6513
1  2020-02-29   2797
2  2020-03-31   7987
3  2020-04-30   5706
4  2020-05-31   6794
5  2020-06-30   8009
6  2020-07-31   6481
7  2020-08-31   9030
8  2020-09-30   5618
9  2020-10-31   6845
10 2020-11-30   6497
11 2020-12-31   6325
12 2021-01-31   7838
13 2021-02-28   8172
14 2021-03-31   3014
15 2021-04-30   4672
16 2021-05-31   6559
17 2021-06-30   6608
18 2021-07-31   9134
19 2021-08-31   9705
20 2021-09-30   6382
21 2021-10-31   9226
22 2021-11-30   2802
23 2021-12-31   7931
24 2022-01-31   6310
25 2022-02-28   9638
26 2022-03-31   3946
27 2022-04-30   9416
28 2022-05-31   9098
29 2022-06-30   7939
30 2022-07-31   7931
31 2022-08-31   8020
32 2022-09-30   9296
33 2022-10-31   6462
34 2022-11-30   5529
35 2022-12-31   3644
36 2023-01-31   7504
37 2023-02-28   4939
38 2023-03-31   4360
39 2023-04-30   9691
40 2023-05-31   9988
41 2023-06-30   4336
42 2023-07-31   5796
43 2023-08-31   8105
44 2023-09-30   2665
45 2023-10-31   4149
46 2023-11-30   9857
47 2023-12-31   4782
48 2024-01-31   8233
49 2024-02-29   6661
50 2024-03-31   2491
51 2024-04-30   7348
52 2024-05-31   5631
53 2024-06-30   8120
54 2024-07-31   7750
55 2024-08-31   3823
56 2024-09-30   7470
57 2024-10-31   3736
58 2024-11-30   6198
59 2024-12-31   3447

In [65]:
dates = pd.date_range(start = "2024-01-01", periods=365,freq="D")
sales = np.random.randint(1000,10000,size = 365)
df2 = pd.DataFrame({"Date":dates,"Sales":sales})
print(df2)

          Date  Sales
0   2024-01-01   3386
1   2024-01-02   7274
2   2024-01-03   4623
3   2024-01-04   8745
4   2024-01-05   8851
..         ...    ...
360 2024-12-26   2805
361 2024-12-27   1361
362 2024-12-28   9155
363 2024-12-29   1107
364 2024-12-30   5628

[365 rows x 2 columns]

In [68]:
dates = pd.date_range(start = "2023-01-01", periods=24, freq="ME")
sales = np.random.randint(2000,10000,size = 24)
df2 = pd.DataFrame({"Date":dates,"Sales":sales})
print(df2)

         Date  Sales
0  2023-01-31   3573
1  2023-02-28   6741
2  2023-03-31   9762
3  2023-04-30   4466
4  2023-05-31   8853
5  2023-06-30   7187
6  2023-07-31   2659
7  2023-08-31   9996
8  2023-09-30   6335
9  2023-10-31   9668
10 2023-11-30   3263
11 2023-12-31   2087
12 2024-01-31   7308
13 2024-02-29   7524
14 2024-03-31   2840
15 2024-04-30   8697
16 2024-05-31   8972
17 2024-06-30   4917
18 2024-07-31   5037
19 2024-08-31   8094
20 2024-09-30   7610
21 2024-10-31   9393
22 2024-11-30   7944
23 2024-12-31   6069

In [69]:
dates = pd.date_range(start = "2024-01-01 00:00:00", periods=72, freq="h")
sales = np.random.randint(2000,10000,size = 72)
df2 = pd.DataFrame({"Date":dates,"Sales":sales})
print(df2)

                  Date  Sales
0  2024-01-01 00:00:00   8912
1  2024-01-01 01:00:00   9925
2  2024-01-01 02:00:00   9039
3  2024-01-01 03:00:00   9176
4  2024-01-01 04:00:00   3872
..                 ...    ...
67 2024-01-03 19:00:00   6313
68 2024-01-03 20:00:00   6734
69 2024-01-03 21:00:00   4890
70 2024-01-03 22:00:00   5858
71 2024-01-03 23:00:00   3337

[72 rows x 2 columns]

In [70]:
dates = pd.date_range(start = "2020-01-01", periods=60, freq="ME")
sales = np.random.randint(2000,10000,size = 60)
df2 = pd.DataFrame({"Date":dates,"Sales":sales})
print(df2)

         Date  Sales
0  2020-01-31   3418
1  2020-02-29   3193
2  2020-03-31   2227
3  2020-04-30   4665
4  2020-05-31   8243
5  2020-06-30   8804
6  2020-07-31   2526
7  2020-08-31   5980
8  2020-09-30   6777
9  2020-10-31   4464
10 2020-11-30   4267
11 2020-12-31   7052
12 2021-01-31   2697
13 2021-02-28   4684
14 2021-03-31   6502
15 2021-04-30   7493
16 2021-05-31   8491
17 2021-06-30   7152
18 2021-07-31   4702
19 2021-08-31   7206
20 2021-09-30   9511
21 2021-10-31   3955
22 2021-11-30   2060
23 2021-12-31   7881
24 2022-01-31   3052
25 2022-02-28   9172
26 2022-03-31   5454
27 2022-04-30   8749
28 2022-05-31   2485
29 2022-06-30   5922
30 2022-07-31   9144
31 2022-08-31   4487
32 2022-09-30   2606
33 2022-10-31   2260
34 2022-11-30   9855
35 2022-12-31   9865
36 2023-01-31   9144
37 2023-02-28   3299
38 2023-03-31   4665
39 2023-04-30   8976
40 2023-05-31   3630
41 2023-06-30   9069
42 2023-07-31   5873
43 2023-08-31   9998
44 2023-09-30   5912
45 2023-10-31   6518
46 2023-11-30   3808
47 2023-12-31   7510
48 2024-01-31   9000
49 2024-02-29   8397
50 2024-03-31   2762
51 2024-04-30   9198
52 2024-05-31   7896
53 2024-06-30   7748
54 2024-07-31   6534
55 2024-08-31   9407
56 2024-09-30   7218
57 2024-10-31   6354
58 2024-11-30   2795
59 2024-12-31   3870