In [ ]:
import pandas as pd

In [ ]:
#Selecting and Filtering
data = {
    "Name": ["Ravi","Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age": [22,24,21,25,23,26,20,27],
    "City": ["Hyderabad","Chennai","Banglore","Hyderabad","Mumbai","Chennai","Banglore","Mumbai"],
    "Salary": [30000,40000,28000,50000,35000,45000,25000,55000]
}

df = pd.DataFrame(data, index = [101,102,103,104,105,106,107,108])
print(df)

       Name  Age       City  Salary
101    Ravi   22  Hyderabad   30000
102   Priya   24    Chennai   40000
103    Arun   21   Banglore   28000
104   Sneha   25  Hyderabad   50000
105   Kiran   23     Mumbai   35000
106  Anjali   26    Chennai   45000
107  Vikram   20   Banglore   25000
108   Meena   27     Mumbai   55000

In [ ]:
#Head
df.head()

      Name  Age       City  Salary
101   Ravi   22  Hyderabad   30000
102  Priya   24    Chennai   40000
103   Arun   21   Banglore   28000
104  Sneha   25  Hyderabad   50000
105  Kiran   23     Mumbai   35000

In [ ]:
#Tail
df.tail()

       Name  Age       City  Salary
104   Sneha   25  Hyderabad   50000
105   Kiran   23     Mumbai   35000
106  Anjali   26    Chennai   45000
107  Vikram   20   Banglore   25000
108   Meena   27     Mumbai   55000

In [ ]:
#information
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 101 to 108
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      int64
 2   City    8 non-null      object
 3   Salary  8 non-null      int64
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes

In [ ]:
#describe
df.describe()

            Age        Salary
count   8.00000      8.000000
mean   23.50000  38500.000000
std     2.44949  10862.780491
min    20.00000  25000.000000
25%    21.75000  29500.000000
50%    23.50000  37500.000000
75%    25.25000  46250.000000
max    27.00000  55000.000000

In [ ]:
#Number of rows in a dataframe
len(df)

8

In [ ]:
#index range of dataframe
df.index

Index([101, 102, 103, 104, 105, 106, 107, 108], dtype='int64')

In [ ]:
#Dimensions of a dataframe
df.shape

(8, 4)

In [ ]:
#Selecting Based on Columns
df[['City','Salary']]

          City  Salary
101  Hyderabad   30000
102    Chennai   40000
103   Banglore   28000
104  Hyderabad   50000
105     Mumbai   35000
106    Chennai   45000
107   Banglore   25000
108     Mumbai   55000

In [ ]:
#Selecting Based on Rows
#Based on integers
df.iloc[0:3]

      Name  Age       City  Salary
101   Ravi   22  Hyderabad   30000
102  Priya   24    Chennai   40000
103   Arun   21   Banglore   28000

In [ ]:
#Based on index
df.loc[104:107]

       Name  Age       City  Salary
104   Sneha   25  Hyderabad   50000
105   Kiran   23     Mumbai   35000
106  Anjali   26    Chennai   45000
107  Vikram   20   Banglore   25000

In [ ]:
df["Salary"]>45000  #Gives Boolean

101    False
102    False
103    False
104     True
105    False
106    False
107    False
108     True
Name: Salary, dtype: bool

In [ ]:
df[df["Salary"]>45000]  #Give the values

      Name  Age       City  Salary
104  Sneha   25  Hyderabad   50000
108  Meena   27     Mumbai   55000